Repository 42-Gang/auth-server, pull requests merged in 2025-04, with the labels that each got.

#3 [FEAT] 1 인증관련 api 개발
  @types/global.d.ts
  eslint.config.mjs
  package.json
  prisma/schema.prisma
  src/app.ts
  src/config.ts
  src/plugins/container.ts
  src/plugins/http.client.ts
  src/plugins/http/got/http.client.ts
  src/plugins/http/interface/http.client.interface.ts
  src/plugins/jwt-plugin.ts
  src/plugins/jwt.module.ts
  src/plugins/kafka.ts
  src/plugins/router.ts
  src/server-config.ts
  src/v1/apis/auth/TokenGenerator.ts
  src/v1/apis/auth/auth.controller.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/auth/auth.schema.ts
  src/v1/apis/auth/auth.service.ts
  src/v1/apis/auth/schemas/login.schema.ts
  src/v1/apis/auth/schemas/refreshAccessToken.schema.ts
  src/v1/apis/auth/schemas/requestVerificationCode.schema.ts
  src/v1/apis/auth/schemas/signup.schema.ts
  src/v1/apis/auth/services/auth.service.ts
  src/v1/apis/auth/services/mail-verification.service.ts
  src/v1/apis/auth/services/token.service.ts
  src/v1/apis/auth/services/user.service.ts
  src/v1/apis/users/user.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.schema.ts
  src/v1/apis/users/users.service.ts
  src/v1/common/constants/topics.ts
  src/v1/common/exceptions/core.error.ts
  src/v1/common/schema/core.schema.ts
  src/v1/common/types/fastify.d.ts
  src/v1/index.ts
  src/v1/kafka/send.mail.kafka.ts
  src/v1/sockets/chat/chat.namespace.ts
  src/v1/storage/cache/interfaces/user.cache.interface.ts
  src/v1/storage/cache/redis/user.cache.repository.ts
  src/v1/storage/database/interfaces/MailVerification.repository.interface.ts
  src/v1/storage/database/interfaces/RefreshToken.repository.interface.ts
  src/v1/storage/database/interfaces/user.repository.interface.ts
  src/v1/storage/database/prisma/MailVerification.repository.ts
  src/v1/storage/database/prisma/RefreshToken.repository.ts
  src/v1/storage/database/prisma/user.repository.ts
  test/plugins/http/got/http.client.spec.ts
  test/v1/apis/auth/auth.service.spec.ts
  test/v1/apis/auth/mail-verification.service.spec.ts
  test/v1/apis/auth/services/auth.service.spec.ts
  test/v1/apis/auth/token.service.spec.ts
  test/v1/apis/auth/user.service.spec.ts
  test/v1/mocks/mockPrisma.ts
  wiremock/docker-compose.yaml
  wiremock/mappings/user-check-email.json
  wiremock/mappings/user-create.json
  wiremock/mappings/users-authenticate.json
Labels: ✨ Feature, 📬 API

#6 [FEATURE] 5 dockerfile 구성
  .dockerignore
  @types/global.d.ts
  Dockerfile
  package.json
  src/server-config.ts
  src/server-utils.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/auth/services/user.service.ts
Labels: ⚙ Setting

#8 [REFACTOR] 1 cors관련설정
  src/server-config.ts
  src/v1/apis/auth/auth.controller.ts
Labels: ⚙ Setting

#10 [REFACTOR] 내부API 보안 설정
  src/app.ts
  src/plugins/router.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/auth/services/auth.service.ts
  src/v1/apis/auth/services/mail-verification.service.ts
  src/v1/apis/auth/services/user.service.ts
  src/v1/common/types/fastify.d.ts
  test/v1/apis/auth/mail-verification.service.spec.ts
Labels: ⚙ Setting, ✨ Feature

#11 [FEATURE] 메일 전송 기능 구현
  @types/global.d.ts
  package.json
  src/mail/mail.consumer.ts
  src/mail/mail.messages.schema.ts
  src/mail/templates/verification.html
  src/mail/verification-code.template.ts
  src/plugins/mailer.ts
  src/server-config.ts
  src/v1/common/constants/topics.ts
  src/v1/kafka/send.mail.kafka.ts
Labels: ✨ Feature

#12 [FIX] error-message 수정
  src/plugins/swagger/swagger-plugin.ts
  src/v1/apis/auth/auth.controller.ts
  src/v1/apis/auth/services/mail-verification.service.ts
  src/v1/apis/auth/services/token.service.ts
  src/v1/apis/auth/services/user.service.ts
  src/v1/common/exceptions/core.error.ts
  test/v1/apis/auth/auth.service.spec.ts
  test/v1/apis/auth/mail-verification.service.spec.ts
Labels: 🐞 BugFix

#14 [REFACTOR] 인증 라우트 internalOnly 제거
  package.json
  src/server-config.ts
  src/v1/apis/auth/auth.route.ts
Labels: 🔨 Refactor
